export const ADD_POST = 'ADD_POST'
export const ADD_COMPLETE = 'ADD_COMPLETE'
export const REMOVE_COMLETE = 'REMOVE_COMPLETE'
export const REMOVE_POST = 'REMOVE_POST'
export const CHANGE_LIST = 'CHANGE_LIST'